import type { Copy, Project } from './types'

const aiCollaboration: Copy = {
  zh: 'AI 辅助受控实现、测试与文档；产品判断、交互决策与最终验收由本人负责。',
  en: 'AI-assisted implementation, testing, and documentation; product judgment, interaction decisions, and final acceptance by Ruyan Qin.',
}

export const projects: Project[] = [
  {
    slug: 'abyss-vr', number: '01', year: '—', engine: 'VR',
    title: { zh: 'Abyss：基于物理的 VR 叙事恐怖体验', en: 'Abyss: Physics-based VR Narrative Horror' },
    shortTitle: { zh: 'Abyss', en: 'Abyss' },
    role: { zh: 'VR 交互与叙事原型设计', en: 'VR interaction and narrative prototyping' },
    premise: { zh: '一段以身体交互、空间尺度和失控感构建宇宙恐怖的 VR 叙事体验。', en: 'A VR narrative experience that builds cosmic horror through embodied interaction, spatial scale, and loss of control.' },
    technicalAngle: { zh: '这款基于物理的 VR 叙事恐怖原型以洛夫克拉夫特式宇宙为背景，探索脆弱感与人类的渺小。手势驱动的移动和交互将玩家身体纳入玩法，物理系统强化不稳定与紧张感；空间沉浸和 3D 音频放大尺度感与对未知的恐惧。', en: 'This physics-based VR narrative horror prototype explores vulnerability and human insignificance within a Lovecraftian cosmic setting. Gesture-driven locomotion and interaction integrate the player’s body into the gameplay, while physics systems reinforce instability and tension. Spatial immersion and 3D audio amplify scale perception and fear of the unknown.' },
    creativeAngle: { zh: '把恐怖从被观看的事件变成身体亲历的处境，突出宇宙尺度下脆弱的人类能动性。', en: 'Transforming horror from something observed into something embodied, with fragile human agency set against a cosmic scale.' },
    contribution: [
      { zh: '以物理交互强调不稳定和失控感', en: 'Used physics-based interaction to emphasise instability and loss of control.' },
      { zh: '使用手部和手指追踪实现手势驱动移动', en: 'Created gesture-driven locomotion using hand and finger tracking.' },
      { zh: '以夸张空间尺度和 3D 音频唤起巨物恐惧', en: 'Used exaggerated spatial scale and 3D audio to evoke megalophobia.' },
      { zh: '在沉浸式 VR 空间中组织环境叙事', en: 'Built environmental storytelling within an immersive VR space.' },
      { zh: '将恐怖体验从观看转化为身体参与', en: 'Shifted horror from observed spectacle to embodied experience.' },
      { zh: '探索宇宙渺小感与脆弱的人类能动性', en: 'Explored cosmic insignificance and fragile human agency.' },
    ],
    capabilities: [{ zh: '物理交互', en: 'Physics interaction' }, { zh: '手部追踪', en: 'Hand tracking' }, { zh: '3D 音频', en: '3D audio' }, { zh: '环境叙事', en: 'Environmental storytelling' }],
    media: { kind: 'image', src: '/media/abyss.jpg', alt: { zh: 'Abyss VR 叙事恐怖体验预览', en: 'Abyss VR narrative horror preview' } },
    extraMedia: [
      { src: '/media/abyss-detail-1.png', alt: { zh: 'Abyss 项目画面一', en: 'Abyss project image one' } },
      { src: '/media/abyss-detail-2.png', alt: { zh: 'Abyss 项目画面二', en: 'Abyss project image two' } },
      { src: '/media/abyss-detail-3.png', alt: { zh: 'Abyss 项目画面三', en: 'Abyss project image three' } },
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=Jfq4dHgv87M',
    tags: [{ zh: 'VR 恐怖', en: 'VR horror' }, { zh: '具身交互', en: 'Embodied interaction' }, { zh: '空间音频', en: 'Spatial audio' }],
  },
  {
    slug: 'ar-graffiti', number: '02', year: '—', engine: 'AR',
    title: { zh: 'AR Graffiti', en: 'AR Graffiti' }, shortTitle: { zh: 'AR Graffiti', en: 'AR Graffiti' },
    role: { zh: 'AR 交互研究与原型设计', en: 'AR interaction research and prototyping' },
    premise: { zh: '比较多种具象与手势输入方式如何影响 AR 创作体验。', en: 'A comparison of tangible and gesture-based input techniques for creative work in AR.' },
    technicalAngle: { zh: '该原型包含直接放置、路径绘制、喷涂、上色和拖放等多种涂鸦交互方式，用于研究不同输入风格如何影响用户偏好、沉浸感、可用性和创意表达。内容基于表面进行空间对齐，并提供实时交互反馈。', en: 'This prototype includes direct placement, path-based drawing, spray painting, coloring, and drag-and-drop manipulation. The interaction modes investigate how different styles influence preference, immersion, usability, and creative expression, with surface-based spatial alignment and real-time feedback.' },
    creativeAngle: { zh: '把 AR 环境变成直觉清晰的创作空间，同时比较不同输入方式的可用性。', en: 'Turning AR into an intuitive creation space while comparing the usability of different input techniques.' },
    contribution: [
      { zh: '实现直接放置与路径绘制', en: 'Implemented direct placement and path-based drawing.' },
      { zh: '实现喷涂、上色与拖放操作', en: 'Implemented spray painting, coloring, and drag-and-drop manipulation.' },
      { zh: '将 AR 内容与真实表面进行空间对齐', en: 'Aligned AR content to real-world surfaces.' },
      { zh: '提供实时交互反馈', en: 'Provided real-time interaction feedback.' },
      { zh: '比较不同 AR 输入方式的可用性', en: 'Compared usability across AR input techniques.' },
      { zh: '探索沉浸环境中的直觉创作工具', en: 'Explored intuitive creation tools in immersive environments.' },
    ],
    capabilities: [{ zh: '空间对齐', en: 'Spatial alignment' }, { zh: '手势交互', en: 'Gesture interaction' }, { zh: '绘制工具', en: 'Drawing tools' }, { zh: '可用性比较', en: 'Usability comparison' }],
    media: { kind: 'image', src: '/media/ar-graffiti.png', alt: { zh: 'AR Graffiti 项目预览', en: 'AR Graffiti project preview' } },
    youtubeUrl: 'https://www.youtube.com/watch?v=IBjiM0_Ek-c',
    tags: [{ zh: 'AR 创作', en: 'AR creation' }, { zh: '手势', en: 'Gestures' }, { zh: '交互研究', en: 'Interaction research' }],
  },
  {
    slug: 'speaking-world', number: '03', year: '—', engine: 'AR + AI',
    title: { zh: 'Speaking World：AR 与 AI 陪伴环境', en: 'Speaking World: AR & AI Companion Environment' },
    shortTitle: { zh: 'Speaking World', en: 'Speaking World' },
    role: { zh: 'AR 与 AI 体验设计', en: 'AR and AI experience design' },
    premise: { zh: '让冰箱、沙发和食物等日常物体成为能够对话的环境伙伴。', en: 'An environment where everyday objects such as fridges, sofas, and food become conversational companions.' },
    technicalAngle: { zh: '该原型通过 AI 增强的 AR 环境探索孤独感。它不设置单一虚拟助手，而是让周围空间本身回应用户，并赋予日常物体声音和个性。集成的 AR 涂鸦功能允许用户留下表达性痕迹，强化个人在空间中的存在。', en: 'This prototype explores loneliness through an AI-augmented AR environment. Instead of a single assistant, the surrounding space responds to the user, giving everyday objects voice and personality. An integrated AR graffiti feature lets users leave expressive marks and reinforce their presence in the space.' },
    creativeAngle: { zh: '把环境重新想象成一种弥散式陪伴，探索空间 AI 如何改变在场感与连接。', en: 'Reimagining the environment as ambient companionship and asking how spatial AI might reshape presence and connection.' },
    contribution: [
      { zh: '设计由 AI 驱动的可对话物体', en: 'Designed AI-powered conversational objects.' },
      { zh: '建立与日常物品的 AR 交互', en: 'Created AR interaction with everyday items.' },
      { zh: '加入用于个人表达的 AR 涂鸦', en: 'Added AR graffiti for personal expression.' },
      { zh: '将环境转化为响应式社交空间', en: 'Turned the environment into a responsive social space.' },
    ],
    capabilities: [{ zh: '对话式 AI', en: 'Conversational AI' }, { zh: '空间 AR', en: 'Spatial AR' }, { zh: '环境交互', en: 'Ambient interaction' }, { zh: 'AR 涂鸦', en: 'AR graffiti' }],
    media: { kind: 'image', src: '/media/speaking-world.png', alt: { zh: 'Speaking World 项目预览', en: 'Speaking World project preview' } },
    youtubeUrl: 'https://www.youtube.com/watch?v=j5jeKZbRmL8',
    tags: [{ zh: '空间 AI', en: 'Spatial AI' }, { zh: '陪伴环境', en: 'Companion environment' }, { zh: 'AR', en: 'AR' }],
  },
  {
    slug: 'emotional-mask', number: '04', year: '2026', engine: 'VR',
    title: { zh: 'Emotional Mask：VR 手部追踪体验', en: 'Emotional Mask: VR Hand-tracking Experience' },
    shortTitle: { zh: 'Emotional Mask', en: 'Emotional Mask' },
    role: { zh: 'VR 具身交互设计', en: 'VR embodied interaction design' },
    premise: { zh: '通过不断扩张或消退的虚拟面具，呈现社会伪装的心理代价。', en: 'A virtual mask that expands or clears to reveal the psychological cost of social masking.' },
    technicalAngle: { zh: '玩家使用代表情绪回应的手势经历不同社交情境。顺从期待会让虚拟面具扩张，逐渐遮挡视野并限制感知；诚实表达则会清除面具、扩大视野并照亮环境。项目以具身交互把抽象社会压力转化为身体和感知层面的体验。', en: 'Players navigate social scenarios using gestures that represent emotional responses. Conforming to expectations expands a virtual mask that obscures vision, while honest self-expression clears it, widens the field of view, and brightens the environment. Embodied interaction turns abstract pressure into a physical, perceptual experience.' },
    creativeAngle: { zh: '用感知变化外化内在冲突，并通过身体选择鼓励自我接纳。', en: 'Externalising internal conflict through perceptual change and encouraging self-acceptance through embodied choice.' },
    contribution: [
      { zh: '设计针对社交情境的手势回应', en: 'Designed gesture-based responses to social scenarios.' },
      { zh: '用面具扩张与消退表现社会顺从和诚实表达', en: 'Used mask expansion and clearing to represent conformity and honest expression.' },
      { zh: '以具身交互外化内在情绪冲突', en: 'Used embodiment to externalise internal emotional conflict.' },
      { zh: '通过视野和环境变化鼓励自我接纳', en: 'Encouraged self-acceptance through changes in perception and environment.' },
    ],
    capabilities: [{ zh: 'VR 手部追踪', en: 'VR hand tracking' }, { zh: '手势输入', en: 'Gesture input' }, { zh: '视野反馈', en: 'Field-of-view feedback' }, { zh: '具身叙事', en: 'Embodied narrative' }],
    scale: { zh: 'Global Game Jam 2026 原型', en: 'Global Game Jam 2026 prototype' },
    media: { kind: 'image', src: '/media/emotional-mask.jpg', alt: { zh: 'Emotional Mask 项目预览', en: 'Emotional Mask project preview' } },
    youtubeUrl: 'https://www.youtube.com/watch?v=AvCc4186Ol4',
    tags: [{ zh: '社会伪装', en: 'Social masking' }, { zh: '手部追踪', en: 'Hand tracking' }, { zh: 'Game Jam', en: 'Game jam' }],
  },
  {
    slug: 'ar-escape-room', number: '05', year: '—', engine: 'AR',
    title: { zh: 'AR Escape Room', en: 'AR Escape Room' }, shortTitle: { zh: 'AR Escape Room', en: 'AR Escape Room' },
    role: { zh: '团队负责人、关卡设计与玩法编程', en: 'Team lead, level design, and gameplay programming' },
    premise: { zh: '把空间谜题嵌入真实环境，让玩家同时观察和操作数字与物理元素。', en: 'Spatial puzzles embedded in the physical environment, requiring interaction with both digital and real-world elements.' },
    technicalAngle: { zh: '虚拟物体锚定在真实空间中，玩家需要移动、观察并操作数字和物理元素。项目结合透视式谜题、机器学习手写数字识别和二维码触发机制，探索空间对齐、真实世界透视与物体识别等 AR 特性。', en: 'Virtual objects are anchored to real-world space, requiring players to move, observe, and interact with digital and physical elements. Passthrough puzzles, machine-learning handwritten digit recognition, and QR triggers explore spatial alignment, real-world passthrough, and object recognition.' },
    creativeAngle: { zh: '让谜题真正依赖 AR 的空间特性，而不是把平面谜题简单悬浮在现实中。', en: 'Making puzzles depend on AR’s spatial affordances rather than simply floating conventional puzzles in the room.' },
    contribution: [
      { zh: '把虚拟物体锚定到真实表面', en: 'Anchored virtual objects to real-world surfaces.' },
      { zh: '设计结合身体移动与数字操作的透视谜题', en: 'Designed passthrough puzzles combining physical movement and digital manipulation.' },
      { zh: '集成基于机器学习的手写数字识别', en: 'Integrated machine-learning handwritten digit recognition.' },
      { zh: '使用二维码检测触发谜题', en: 'Used QR-code detection as an interactive puzzle trigger.' },
      { zh: '作为团队负责人推动项目协调', en: 'Facilitated project coordination as team lead.' },
      { zh: '规划空间 AR 谜题的关卡布局', en: 'Conceptualised and mapped spatial AR puzzle layouts.' },
      { zh: '实现数字识别和二维码玩法逻辑', en: 'Implemented digit-recognition and QR-trigger gameplay logic.' },
    ],
    capabilities: [{ zh: '空间锚定', en: 'Spatial anchoring' }, { zh: '透视 AR', en: 'Passthrough AR' }, { zh: '机器学习识别', en: 'ML recognition' }, { zh: '二维码检测', en: 'QR detection' }],
    scale: { zh: '团队项目', en: 'Team project' },
    media: { kind: 'image', src: '/media/ar-escape-room.png', alt: { zh: 'AR Escape Room 项目预览', en: 'AR Escape Room project preview' } },
    youtubeUrl: 'https://www.youtube.com/watch?v=Qz9FfWEAgcA',
    tags: [{ zh: '空间谜题', en: 'Spatial puzzles' }, { zh: '机器学习', en: 'Machine learning' }, { zh: '团队项目', en: 'Team project' }],
  },
  {
    slug: 'white-lavender', number: '08', year: '—', engine: 'Game Remake',
    title: { zh: 'White Lavender：游戏复刻练习', en: 'White Lavender: Game Remake Practice' },
    shortTitle: { zh: 'White Lavender', en: 'White Lavender' },
    role: { zh: '核心系统复刻练习', en: 'Core-systems remake practice' },
    premise: { zh: '围绕《White Lavender》核心机制进行的技术复刻练习。', en: 'A technical remake practice focused on recreating the core mechanics of White Lavender.' },
    technicalAngle: { zh: '该项目聚焦于复刻《White Lavender》的核心系统，并分别实现战斗、界面和对话模块。', en: 'This project focuses on recreating the core mechanics of White Lavender through combat, UI, and dialogue systems.' },
    creativeAngle: { zh: '通过拆解并重建既有游戏系统，练习从可见体验反推技术结构。', en: 'Reconstructing visible game behavior as a way to practise reasoning from experience back to system structure.' },
    contribution: [
      { zh: '复刻战斗系统', en: 'Recreated the combat system.' },
      { zh: '复刻 UI 系统', en: 'Recreated the UI system.' },
      { zh: '复刻对话系统', en: 'Recreated the dialogue system.' },
    ],
    capabilities: [{ zh: '战斗系统', en: 'Combat system' }, { zh: 'UI 系统', en: 'UI system' }, { zh: '对话系统', en: 'Dialogue system' }],
    media: { kind: 'image', src: '/media/white-lavender.png', alt: { zh: 'White Lavender 游戏复刻预览', en: 'White Lavender remake preview' } },
    youtubeUrl: 'https://www.youtube.com/watch?v=YqOI3-PyRKA',
    tags: [{ zh: '游戏复刻', en: 'Game remake' }, { zh: '战斗', en: 'Combat' }, { zh: 'UI', en: 'UI' }],
  },
  {
    slug: 'claw-machine', number: '07', year: '2026', engine: 'Unity',
    title: { zh: '握力抓娃娃机', en: 'Force-sensitive Claw Machine' },
    shortTitle: { zh: '抓娃娃机', en: 'Claw Machine' },
    role: { zh: '交互设计、玩法系统与原型开发', en: 'Interaction design, gameplay systems, and prototype development' },
    collaboration: aiCollaboration,
    premise: { zh: '把抓娃娃从位置判断，变成双手协作的力度挑战。', en: 'A claw machine where holding with the right force matters as much as positioning.' },
    technicalAngle: { zh: '左手移动抓手，右手启动抓取并维持握力。每个玩具有独立力度窗口，持续越界、主动松手与自动投放会进入不同结果。键鼠模拟先跑通完整循环，再为真实手套保留统一输入路径。', en: 'The left hand moves the claw while the right initiates and sustains the grip. Configurable force windows, timed failure states, intentional release, and simulated input make the loop testable before final glove tuning.' },
    creativeAngle: { zh: '“抓住”不再只是按下按钮，而是要用身体感觉找到刚刚好的力。不同娃娃像有不同脾气，太紧、太松都会改变结果。', en: 'Grabbing becomes a small act of judgment: hold just firmly enough. Each toy asks for a different touch, and too much force can be as meaningful as too little.' },
    contribution: [
      { zh: '设计双手分工，将抓取转化为持续力度控制', en: 'Designed a two-hand division of labor that turns grabbing into continuous force control.' },
      { zh: '定义下降、闭合、搬运、掉落、投放与回位流程', en: 'Defined the descent, close, carry, drop, delivery, and reset flow.' },
      { zh: '为不同物体设计独立力度窗口与连续越界判定', en: 'Designed independent force windows and sustained out-of-range checks for different objects.' },
      { zh: '协调夹爪动画、物理释放、三爪控制与局部形变', en: 'Coordinated claw animation, physical release, three-prong control, and local deformation.' },
      { zh: '建立键鼠模拟与硬件输入共用的控制接口', en: 'Built a shared control interface for keyboard simulation and hardware input.' }
    ],
    capabilities: [
      { zh: 'Unity 玩法状态机', en: 'Unity gameplay states' }, { zh: '握力输入映射', en: 'Grip-force mapping' },
      { zh: '键鼠硬件模拟', en: 'Hardware input simulation' }, { zh: '失败与恢复边界', en: 'Failure and recovery boundaries' }
    ],
    workflow: { zh: ['体验目标', '读取工程', '拆成力度与状态规则', '模拟输入原型', '试玩与收缩', '测试并同步文档'], en: ['Experience goal', 'Inspect project', 'Define force and state rules', 'Simulated-input prototype', 'Play and simplify', 'Test and document'] },
    status: { zh: '集成原型。主循环与力度反馈已实现；最终场景组装、结果反馈、物体复位与真实双手参数仍需验收。', en: 'Integration prototype. The main loop and force feedback are implemented; final scene assembly, result feedback, object reset, and dual-hand tuning still require validation.' },
    media: { kind: 'image', src: '/media/claw-machine-original-style-cover.png', alt: { zh: '柔和粉蓝色 3D 风格的抓娃娃机场景', en: 'Soft pastel 3D claw-machine scene' } },
    tags: [{ zh: '体感交互', en: 'Embodied input' }, { zh: '游戏系统', en: 'Game systems' }, { zh: '快速验证', en: 'Rapid validation' }]
  },
  {
    slug: 'four-way-kitchen', number: '06', year: '2026', engine: 'Unity',
    title: { zh: '四面厨房', en: 'Four-way Kitchen' }, shortTitle: { zh: '四面厨房', en: 'Four-way Kitchen' },
    role: { zh: '游戏设计、多输入系统与原型开发', en: 'Game design, multi-input systems, and prototype development' },
    collaboration: aiCollaboration,
    premise: { zh: '一套不因输入设备改变而重写的厨房玩法循环。', en: 'A kitchen loop designed to survive changing input devices.' },
    technicalAngle: { zh: '围绕四面柜台建立取材、切菜、烹饪、装盘、投掷与交付，并让键鼠、EMG、摄像头和双手手套进入同一套玩法语义。断线、超时、输入残留和对角意图都被作为真实体验问题处理。', en: 'Sourcing, chopping, cooking, plating, throwing, and delivery share one gameplay language across keyboard, EMG, camera, and dual-glove input. Disconnects, stale signals, timeout, and diagonal intent are treated as experience problems.' },
    creativeAngle: { zh: '厨房被压缩成围绕身体的四个方向：左手负责连续移动，右手负责拿放、处理和投掷。复杂设备最终被翻译成直觉清楚的动作分工。', en: 'The kitchen wraps around the body in four directions. One hand navigates continuously; the other picks up, prepares, and throws, turning complicated devices into a clear physical division of labor.' },
    contribution: [
      { zh: '设计取材、加工、烹饪、装盘、投掷与交付循环', en: 'Designed the sourcing, preparation, cooking, plating, throwing, and delivery loop.' },
      { zh: '将连续移动与拿放、切菜、四向投掷分配给双手', en: 'Split continuous movement and discrete pickup, chopping, and four-way throwing actions across both hands.' },
      { zh: '用确定性抛物线替代不可控的自由物理投掷', en: 'Replaced uncontrolled free-physics throws with a deterministic ballistic trajectory.' },
      { zh: '统一键鼠、EMG、摄像头与手套的玩法语义', en: 'Unified keyboard, EMG, camera, and glove input behind the same gameplay semantics.' },
      { zh: '处理对角意图、输入残留、超时与断线释放', en: 'Handled diagonal intent, stale input, timeout, and disconnect release behavior.' }
    ],
    capabilities: [{ zh: '多设备输入整合', en: 'Multi-device integration' }, { zh: '完整玩法循环', en: 'Complete gameplay loop' }, { zh: '超时与断线处理', en: 'Timeout and disconnect handling' }, { zh: '体感动作映射', en: 'Embodied action mapping' }],
    workflow: { zh: ['玩法循环', '键鼠灰盒', '扩展系统', '模拟设备链路', '接入真实输入', '诊断失败', '修订映射'], en: ['Core loop', 'Keyboard graybox', 'Expand systems', 'Simulate device paths', 'Integrate input', 'Diagnose failures', 'Revise mappings'] },
    status: { zh: '多输入原型。核心系统已经接入；完整 Play Mode、真实双手手感、摄像头性能与 Windows 构建仍待验收。', en: 'Multi-input prototype. Core systems are integrated; full Play Mode, dual-glove feel, camera performance, and the Windows build still require validation.' },
    media: { kind: 'image', src: '/media/four-way-kitchen-polaroid.webp', alt: { zh: '四面厨房游戏画面，包含食材柜、砧板、炉灶与中央角色', en: 'Four-sided kitchen gameplay with ingredient stations, chopping boards, stoves, and a central character' } },
    tags: [{ zh: 'XR 输入', en: 'XR input' }, { zh: 'EMG', en: 'EMG' }, { zh: '玩法原型', en: 'Gameplay prototype' }]
  },
  {
    slug: 'cat-teaser', number: '09', year: '2026', engine: 'Unity',
    title: { zh: '逗猫绳 2D', en: 'Cat Teaser 2D' }, shortTitle: { zh: '逗猫绳', en: 'Cat Teaser' },
    role: { zh: '交互设计、物理与行为原型开发', en: 'Interaction, physics, and behavior prototyping' },
    collaboration: aiCollaboration,
    premise: { zh: '让动作经过一根有延迟的绳子，也让猫真的能够扑空。', en: 'A physics toy where motion travels through a rope and the cat can genuinely miss.' },
    technicalAngle: { zh: '玩家移动手柄，动作经自定义绳索产生延迟与惯性。猫会观察、蓄力并提前锁定起跳点；速度与加速度双阈值、边界约束、多目标行为与鼠标/腕带共用路径共同组成可测试的交互系统。', en: 'A custom rope simulation carries motion with lag and inertia. The cat observes, winds up, and commits early; two-threshold flick detection, boundaries, multiple targets, and mouse/wristband parity make the interaction testable.' },
    creativeAngle: { zh: '玩家控制的不是羽毛，而是羽毛前面的手柄。那一点迟到的摆动，让猫的预判、扑空和玩家的临场欺骗都真正成立。', en: 'You control the handle, not the feather. That small delay makes anticipation, deception, and a well-timed miss feel real.' },
    contribution: [
      { zh: '定义“控制手柄端、由绳索传力”的核心交互', en: 'Defined the core interaction around controlling the handle while force travels through the rope.' },
      { zh: '调校绳索惯性、羽毛漂浮与速度/加速度甩动判定', en: 'Tuned rope inertia, feather drift, and velocity/acceleration-based flick detection.' },
      { zh: '设计猫咪观察、蓄力、锁点、扑跃与扑空行为', en: 'Designed the cat’s observation, wind-up, target lock, pounce, and miss behaviors.' },
      { zh: '扩展鱼、双猫、可控小鸟与三关渐进玩法', en: 'Expanded the prototype with fish, two cats, a controllable bird, and three progressive stages.' },
      { zh: '打通鼠标与腕带输入，并主动简化硬件映射路径', en: 'Unified mouse and wristband input while deliberately simplifying the hardware mapping path.' }
    ],
    capabilities: [{ zh: '自定义绳索物理', en: 'Custom rope physics' }, { zh: '行为状态设计', en: 'Behavior state design' }, { zh: '腕带输入', en: 'Wristband input' }, { zh: 'Edit/Play Mode 测试', en: 'Edit/Play Mode tests' }],
    workflow: { zh: ['追逐概念', '拆物理规则', '绳索与行为原型', '观察机械感', '加入预判与锁点', '比较硬件路径', '主动简化'], en: ['Chase premise', 'Define physics', 'Rope and behavior prototype', 'Observe timing', 'Add anticipation', 'Compare hardware paths', 'Simplify'] },
    status: { zh: '可玩交互原型，具有三关、两只猫与多种目标。真实腕带手感和端到端延迟仍待实机确认。', en: 'Playable interaction prototype with three scenarios, two cats, and multiple targets. Wristband feel and end-to-end latency still need device validation.' },
    media: { kind: 'image', src: '/media/cat-teaser-polaroid.webp', alt: { zh: '两只猫、鱼与动态符号组成的逗猫绳 2D 插画场景', en: 'Illustrated Cat Teaser 2D scene with two cats, a fish, and playful motion marks' } },
    tags: [{ zh: '物理玩具', en: 'Physics toy' }, { zh: '动物行为', en: 'Animal behavior' }, { zh: '交互收缩', en: 'Interaction simplification' }]
  },
  {
    slug: 'mole-rhythm', number: '10', year: '2026', engine: 'Unity',
    title: { zh: '地底五重奏', en: 'Mole Rhythm' }, shortTitle: { zh: '地底五重奏', en: 'Mole Rhythm' },
    role: { zh: '玩法、谱面与交互原型开发', en: 'Gameplay, chart, and interaction prototyping' },
    collaboration: aiCollaboration,
    premise: { zh: '五根手指不是打地鼠，而是在和五位地底乐手共同演奏。', en: 'Five fingers perform with five underground musicians.' },
    technicalAngle: { zh: '成熟音频分析寻找节拍与起音，自定义规则控制量化、密度、弱指压力和双指比例。离线生成保证谱面可复现，DSP 时间与可调判定窗口保持演奏一致。', en: 'Audio analysis finds beats and onsets; custom rules handle quantization, density, weaker-finger load, and two-finger events. Reproducible offline charts, DSP timing, and adjustable windows keep play consistent.' },
    creativeAngle: { zh: '地鼠不再是敌人，而是五位需要配合的演奏者。手套里的每根手指都有自己的声部，难度设计首先照顾第一次戴上设备的人。', en: 'The moles are performers, not targets. Each finger gets a part, while the chart first respects the ergonomics of someone trying the glove for the first time.' },
    contribution: [
      { zh: '将传统打地鼠重构为五指对应五轨的节奏玩法', en: 'Reframed traditional whack-a-mole as a five-finger, five-lane rhythm game.' },
      { zh: '为展会新手定义密度、弱指压力与双指人体工学规则', en: 'Defined density, weaker-finger load, and two-finger ergonomic rules for first-time exhibition players.' },
      { zh: '建立音频分析、节拍量化和确定性自动谱面流程', en: 'Built an audio-analysis, beat-quantization, and deterministic chart-generation pipeline.' },
      { zh: '将多音轨方案收缩为更稳定的单音乐视觉判定', en: 'Reduced the multi-track approach to a more reliable single-track visual judgment system.' },
      { zh: '制作 Normal、Easy、Very Easy 与可调判定窗口', en: 'Created Normal, Easy, and Very Easy modes with adjustable timing windows.' }
    ],
    capabilities: [{ zh: '音频分析', en: 'Audio analysis' }, { zh: '规则化谱面生成', en: 'Rule-based chart generation' }, { zh: 'DSP 判定', en: 'DSP timing' }, { zh: '人体工学约束', en: 'Ergonomic constraints' }],
    workflow: { zh: ['五指演奏概念', '展开音频方案', '检查真实素材', '删除多余依赖', '离线生成谱面', '导入与判定测试', '制作简单难度'], en: ['Five-finger premise', 'Explore audio paths', 'Inspect real material', 'Remove dependencies', 'Generate charts offline', 'Test timing', 'Create easier variants'] },
    status: { zh: 'Normal、Easy 与 Very Easy 谱面及视觉反馈已实现；完整 Play Mode 验收、手套误触和音频偏移仍在调校。', en: 'Normal, Easy, and Very Easy charts and feedback are implemented; full Play Mode acceptance, glove false triggers, and audio offset still need tuning.' },
    media: { kind: 'image', src: '/media/mole-rhythm-polaroid.webp', alt: { zh: '五只地鼠乐手与下落木槌组成的像素节奏游戏画面', en: 'Pixel-art rhythm game with five mole performers and a falling mallet' } },
    extraMedia: [{ src: '/media/mole-chart.png', alt: { zh: '地底五重奏谱面数据', en: 'Mole Rhythm chart data' } }],
    tags: [{ zh: '音乐交互', en: 'Musical interaction' }, { zh: '自动谱面', en: 'Generated charts' }, { zh: '五指输入', en: 'Five-finger input' }]
  },
  {
    slug: 'gothic-hunter', number: '11', year: '2026', engine: 'Godot',
    title: { zh: 'Gothic Hunter', en: 'Gothic Hunter' }, shortTitle: { zh: 'Gothic Hunter', en: 'Gothic Hunter' },
    role: { zh: '游戏设计、战斗系统与快速灰盒开发', en: 'Game design, combat systems, and rapid graybox development' },
    collaboration: aiCollaboration,
    premise: { zh: '把一份玩法简报快速做成可完整跑局的俯视角生存灰盒。', en: 'A game brief turned rapidly into a complete top-down survival graybox.' },
    technicalAngle: { zh: '确定性的三幕流程、四种成长武器、两种大招、精英与 Boss 组成约五分钟跑局。对象池、输入抽象、生成器和自动化检查让灰盒既能快速生长，也能持续验证。', en: 'A deterministic three-act run combines four evolving weapons, two ultimates, elites, and a boss. Pooling, input abstraction, generators, and automated checks keep the graybox fast to extend and possible to verify.' },
    creativeAngle: { zh: '先用最少的图形和临时声音找到“越来越失控但仍能读懂”的战斗节奏。可见的武器成长和三幕压力，比正式美术更早决定这个原型是否成立。', en: 'Minimal shapes and temporary sound found the combat rhythm first: increasingly chaotic, but still legible. Visible weapon growth and three-act pressure mattered before final art.' },
    contribution: [
      { zh: '定义约五分钟、三幕递进的俯视角生存跑局', en: 'Defined an approximately five-minute, three-act top-down survival run.' },
      { zh: '设计四种成长武器、两种大招、精英与 Boss', en: 'Designed four evolving weapons, two ultimates, elites, and a boss.' },
      { zh: '通过试玩持续调整敌人密度、伤害、掉落与弹道', en: 'Continuously tuned enemy density, damage, drops, and projectile patterns through playtesting.' },
      { zh: '建立对象池、空间索引与高压战斗性能验证', en: 'Built object pooling, spatial indexing, and high-pressure combat performance validation.' },
      { zh: '用遥测、自动化跑局和录屏验证实际完成度', en: 'Used telemetry, automated runs, and recordings to verify actual completeness.' }
    ],
    capabilities: [{ zh: 'Godot 快速开发', en: 'Rapid Godot development' }, { zh: '战斗节奏与数值', en: 'Combat pacing' }, { zh: '自动化跑局验证', en: 'Automated run checks' }, { zh: '输入抽象', en: 'Input abstraction' }],
    workflow: { zh: ['玩法简报', '建立灰盒', '实际运行与录屏', '指出密度问题', '调整系统与数值', '自动跑局检查', '人工判断'], en: ['Game brief', 'Build graybox', 'Run and record', 'Identify pacing issues', 'Tune systems and values', 'Automated run checks', 'Human judgment'] },
    status: { zh: '可玩灰盒，有实际运行录屏和结构化检查。正式美术、声音与目标硬件性能仍属后续工作。', en: 'Playable graybox with recorded runtime proof and structured checks. Final art, audio, and target-hardware profiling remain future work.' },
    media: { kind: 'video', src: '/media/gothic-hunter.mp4', alt: { zh: 'Gothic Hunter 实机灰盒视频', en: 'Gothic Hunter runtime graybox' } },
    extraMedia: [{ src: '/media/gothic-hunter.jpg', alt: { zh: 'Gothic Hunter 游戏画面', en: 'Gothic Hunter gameplay' } }],
    tags: [{ zh: '快速灰盒', en: 'Rapid graybox' }, { zh: '战斗系统', en: 'Combat systems' }, { zh: '自动验证', en: 'Automated validation' }]
  }
]
